repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
      name: Check added large files
    - id: check-json
      name: Check json
    - id: check-merge-conflict
      name: Check merge conflict
    - id: check-yaml
      name: Check yaml
    - id: check-toml
      name: Check toml
    - id: end-of-file-fixer
      name: End of file fixer
    - id: pretty-format-json
      name: Pretty format json
      args:
        - --autofix
    - id: trailing-whitespace
      name: Trailing whitespace
